ARG BASE_IMAGE=ghcr.io/anomalyco/opencode:latest
FROM ${BASE_IMAGE}

COPY --chmod=0755 run_opencode_task.sh /usr/local/bin/run_opencode_task.sh
COPY --chmod=0755 run_claudecode_task.sh /usr/local/bin/run_claudecode_task.sh
