#!/bin/sh
set -eu

: "${CLOUDCLAW_WORKSPACE:?missing CLOUDCLAW_WORKSPACE}"

OPENCLAW_SHARED_CONFIG_DIR="${OPENCLAW_SHARED_CONFIG_DIR:-/workspace/.config/openclaw}"
OPENCLAW_USER_CONFIG_FILE="${OPENCLAW_USER_CONFIG_FILE:-$CLOUDCLAW_WORKSPACE/openclaw.user.json}"
OPENCLAW_MODEL_NAME="${OPENCLAW_MODEL_NAME:-}"
OPENCLAW_AGENT_NAME="${OPENCLAW_AGENT_NAME:-}"
OPENCLAW_ATTACH="${OPENCLAW_ATTACH:-}"
OPENCLAW_RUN_FORMAT="${OPENCLAW_RUN_FORMAT:-default}"
OPENCLAW_PERSIST_MODE="${OPENCLAW_PERSIST_MODE:-auto}"
OPENCLAW_HOME="${OPENCLAW_HOME:-$CLOUDCLAW_WORKSPACE/.openclaw-home}"
OPENCLAW_STATE_SUBDIR="${OPENCLAW_STATE_SUBDIR:-openclaw}"
OPENCLAW_WORKSPACE_CONFIG_DIRNAME="${OPENCLAW_WORKSPACE_CONFIG_DIRNAME:-.openclaw}"

if [ -z "${OPENCLAW_BIN:-}" ]; then
  if command -v openclaw >/dev/null 2>&1; then
    OPENCLAW_BIN="openclaw"
  else
    OPENCLAW_BIN="opencode"
  fi
fi

export OPENCODE_BIN="$OPENCLAW_BIN"
export OPENCODE_SHARED_CONFIG_DIR="$OPENCLAW_SHARED_CONFIG_DIR"
export OPENCODE_USER_CONFIG_FILE="$OPENCLAW_USER_CONFIG_FILE"
export OPENCODE_MODEL_NAME="$OPENCLAW_MODEL_NAME"
export OPENCODE_AGENT_NAME="$OPENCLAW_AGENT_NAME"
export OPENCODE_ATTACH="$OPENCLAW_ATTACH"
export OPENCODE_RUN_FORMAT="$OPENCLAW_RUN_FORMAT"
export OPENCODE_PERSIST_MODE="$OPENCLAW_PERSIST_MODE"
export OPENCODE_HOME="$OPENCLAW_HOME"
export OPENCODE_STATE_SUBDIR="$OPENCLAW_STATE_SUBDIR"
export OPENCODE_WORKSPACE_CONFIG_DIRNAME="$OPENCLAW_WORKSPACE_CONFIG_DIRNAME"

exec /usr/local/bin/run_opencode_task.sh "$@"
